### ISSUE TITLE
Execution failed for cron line

### ISSUE THREAD

**Issue by thomo** [thomo/valuestable#1]
valuestable 1.4.1

```shell
Execution failed for task ':valuesTable'.
> com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning an alias
   in 'reader', line 45, column 13:
            cron: * * * * * *   # every second
                  ^
  unexpected character found  (32)
   in 'reader', line 45, column 14:
            cron: * * * * * *   # every second
                   ^
  
   at [Source: (File); line: 45, column: 11]
```

line in values.yaml:
```yaml
eventConsumer:
  scheduler:
    regular:
      cron: * * * * * *   # every second
```
